{{- if .Values.bitcoinapi.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name | default "aks-task" }}-bitcoinapi-hpa
  labels:
    app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
  minReplicas: {{ .Values.bitcoinapi.hpa.minReplicas | default "10" }}
  maxReplicas: {{ .Values.bitcoinapi.hpa.maxReplicas | default "2" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.bitcoinapi.hpa.targetCPUUtilizationPercentage | default "50" }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.bitcoinapi.hpa.targetMemoryUtilizationPercentage | default "70" }}
{{- end }}