apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name | default "aks-task" }}-bitcoinapi-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Chart.Name | default "aks-task" }}-restapi
