apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | default "aks-task" }}-bitcoinapi-srv
  labels:
    app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi