apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name | default "aks-task" }}-restapi-netpol
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name | default "aks-task" }}-restapi
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - podSelector:
            matchLabels:
              app: {{ .Chart.Name }}-restapi
  egress:
    - ports:
        - protocol: TCP
          port: http
      to:
        - podSelector:
            matchLabels:
              app: {{ .Chart.Name | default "aks-task" }}-bitcoinapi
