bitcoinapi:
  docker_image_version: 1.0.0

  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 150Mi

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 70

restapi:
  docker_image_version: 1.0.0

  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 150Mi

  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 70
